version: '3'
services:
  raremetal:
    image: "ldserver:latest"
    environment:
      - FLASK_APP=rest/raremetal
      - RAREMETAL_CONFIG_DATA
      - RAREMETAL_WORKERS
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: "on-failure"
    working_dir: /home/ldserver
    command: /bin/bash -c "flask add-yaml ${RAREMETAL_CONFIG_DATA} && gunicorn -b 0.0.0.0:5000 -w ${RAREMETAL_WORKERS} -k gevent --pythonpath rest 'raremetal:create_app()'"

  redis:
    image: "redis:alpine"
