version: '3'
services:
  ldserver:
    build: .
    environment:
      - FLASK_APP=rest/ldserver
    env_file: .env
    ports:
      - "${LDSERVER_PORT}:${LDSERVER_PORT}"
    depends_on:
      - redis
    working_dir: /home/ldserver
    command: /bin/bash -c "source $$LDSERVER_CONFIG_SCRIPT && gunicorn -b 0.0.0.0:$$LDSERVER_PORT -w $$LDSERVER_WORKERS -k gthread --pythonpath rest 'ldserver:create_app()'"

  raremetal:
    build: .
    environment:
      - FLASK_APP=rest/raremetal
    env_file: .env
    ports:
      - "${RAREMETAL_PORT}:${RAREMETAL_PORT}"
    depends_on:
      - redis
    working_dir: /home/ldserver
    command: /bin/bash -c "flask add-yaml $$RAREMETAL_CONFIG_DATA && gunicorn -b 0.0.0.0:$$RAREMETAL_PORT -w $$RAREMETAL_WORKERS -k gthread --pythonpath rest 'raremetal:create_app()'"

  redis:
    image: "redis:5.0-alpine"
